/**
 * AI Task Prioritization Engine
 * 
 * Calculates AI scores for farm tasks based on 4 weighted factors:
 * - Urgency (40%): due date proximity
 * - Category Risk (25%): inherent risk by task category
 * - Farm Impact (20%): how critical to farm operations
 * - AI Insights (15%): contextual boosts from pest/crop/order data
 */

// Category risk scores (0-25 scale)
const CATEGORY_RISK = {
    pest: 25,       // Very high - immediate threat to crops
    irrigation: 22, // High - water stress damages plants
    harvest: 20,    // High - time-sensitive yield collection
    orders: 20,     // High - revenue and customer satisfaction
    crop: 15,       // Medium - important but planned
    equipment: 12,  // Medium - operational but can schedule
    inventory: 10,  // Medium-low - stock management
    manual: 8,      // Low - user-defined general tasks
    planting: 15,   // Medium (legacy category)
    pest_control: 25, // Very high (legacy category)
    maintenance: 12,  // Medium (legacy category)
    harvesting: 20,   // High (legacy category)
    watering: 18,     // High (legacy category)
    fertilizing: 14,  // Medium (legacy category)
    weeding: 10,      // Medium-low (legacy category)
    monitoring: 12,   // Medium (legacy category)
    other: 5          // Low
};

// Farm impact scores (0-20 scale)
const IMPACT_SCORES = {
    yield: 20,
    sales: 18,
    maintenance: 12,
    general: 8
};

// Category to impact mapping
const CATEGORY_IMPACT = {
    pest: 'yield',
    pest_control: 'yield',
    harvest: 'sales',
    harvesting: 'sales',
    orders: 'sales',
    irrigation: 'yield',
    watering: 'yield',
    crop: 'yield',
    planting: 'yield',
    fertilizing: 'yield',
    equipment: 'maintenance',
    inventory: 'maintenance',
    weeding: 'maintenance',
    monitoring: 'maintenance',
    maintenance: 'maintenance',
    manual: 'general',
    other: 'general'
};

/**
 * Calculate urgency score (0-40)
 * @param {Date} dueDate 
 * @returns {number} urgency score
 */
function calculateUrgency(dueDate) {
    if (!dueDate) return 10; // No deadline = low urgency

    const now = new Date();
    const due = new Date(dueDate);
    const diffMs = due.getTime() - now.getTime();
    const diffHours = diffMs / (1000 * 60 * 60);
    const diffDays = diffHours / 24;

    // Overdue → max urgency
    if (diffHours < 0) return 40;

    // Due within 24 hours → very urgent
    if (diffHours <= 24) return 38;

    // Due within 3 days → high urgency
    if (diffDays <= 3) return 32;

    // Due within 7 days → medium-high urgency
    if (diffDays <= 7) return 25;

    // Due within 14 days → medium urgency
    if (diffDays <= 14) return 18;

    // Due within 30 days → low-medium urgency
    if (diffDays <= 30) return 10;

    // Due later → minimal urgency
    return 5;
}

/**
 * Calculate category risk score (0-25)
 * @param {string} category 
 * @returns {number} category risk score
 */
function calculateCategoryRisk(category) {
    return CATEGORY_RISK[category] || CATEGORY_RISK.other;
}

/**
 * Calculate farm impact score (0-20)
 * @param {string} category 
 * @returns {number} farm impact score
 */
function calculateFarmImpact(category) {
    const impactKey = CATEGORY_IMPACT[category] || 'general';
    return IMPACT_SCORES[impactKey];
}

/**
 * Calculate AI insights boost (0-15)
 * @param {Object} task 
 * @param {Object} context - Optional context with pest severity, crop stage, order deadlines
 * @returns {number} AI insights score
 */
function calculateAIInsights(task, context = {}) {
    let score = 0;

    // Pest tasks get additional boost based on severity
    if (task.category === 'pest' || task.category === 'pest_control') {
        score += 8;
        if (context.pestSeverity === 'high') score += 5;
        if (context.pestSeverity === 'critical') score += 7;
    }

    // Crop stage criticality
    if (task.category === 'crop' || task.category === 'planting' || task.category === 'harvest' || task.category === 'harvesting') {
        if (context.cropStage === 'harvest') score += 6;
        else if (context.cropStage === 'flowering') score += 4;
        else if (context.cropStage === 'growth') score += 3;
    }

    // Order deadline proximity
    if (task.category === 'orders' || task.source === 'order') {
        if (context.orderDeadlineNear) score += 5;
        score += 3; // Base boost for order-related
    }

    // Auto-generated tasks from real detections get a boost
    if (task.autoGenerated) {
        score += 3;
    }

    // Source-based boosts
    if (task.source === 'pest_detection') score += 5;
    if (task.source === 'calendar') score += 2;

    return Math.min(score, 15);
}

/**
 * Map AI score to priority label
 * @param {number} score 0-100
 * @returns {string} priority label
 */
function scoreToPriority(score) {
    if (score >= 80) return 'critical';
    if (score >= 60) return 'high';
    if (score >= 40) return 'medium';
    return 'low';
}

/**
 * Generate human-readable AI reason
 * @param {Object} task 
 * @param {Object} scores - Individual factor scores
 * @returns {string} explanation
 */
function generateAIReason(task, { urgency, categoryRisk, farmImpact, aiInsights }) {
    const parts = [];

    // Urgency explanation
    if (task.dueDate) {
        const now = new Date();
        const due = new Date(task.dueDate);
        const diffMs = due.getTime() - now.getTime();
        const diffHours = diffMs / (1000 * 60 * 60);
        const diffDays = Math.round(diffHours / 24);

        if (diffHours < 0) {
            parts.push(`Overdue by ${Math.abs(Math.round(diffHours / 24))} days`);
        } else if (diffHours <= 24) {
            parts.push('Due within 24 hours');
        } else if (diffDays <= 3) {
            parts.push(`Due in ${diffDays} days`);
        } else {
            parts.push(`Due in ${diffDays} days`);
        }
    } else {
        parts.push('No set deadline');
    }

    // Category explanation
    const catLabels = {
        pest: 'Pest control task',
        pest_control: 'Pest control task',
        orders: 'Order fulfillment task',
        harvest: 'Harvest task',
        harvesting: 'Harvest task',
        irrigation: 'Irrigation task',
        watering: 'Water management task',
        crop: 'Crop management task',
        planting: 'Planting task',
        equipment: 'Equipment task',
        inventory: 'Inventory task',
        manual: 'Manual task',
        maintenance: 'Maintenance task',
        fertilizing: 'Fertilization task',
        weeding: 'Weeding task',
        monitoring: 'Monitoring task'
    };
    parts.push(catLabels[task.category] || 'General task');

    // Source explanation
    if (task.source === 'pest_detection') {
        parts.push('Auto-generated from pest detection');
    } else if (task.source === 'calendar') {
        parts.push('From planting calendar');
    } else if (task.source === 'order') {
        parts.push('From marketplace order');
    } else if (task.source === 'ai') {
        parts.push('AI-suggested task');
    }

    // Priority justification
    const totalScore = urgency + categoryRisk + farmImpact + aiInsights;
    if (totalScore >= 80) {
        parts.push('CRITICAL priority - immediate action required');
    } else if (totalScore >= 60) {
        parts.push('High priority - address soon');
    } else if (totalScore >= 40) {
        parts.push('Medium priority - plan accordingly');
    } else {
        parts.push('Low priority - can be scheduled later');
    }

    return parts.join(' | ');
}

/**
 * Main prioritization function
 * @param {Array} tasks - Array of task objects
 * @param {Object} context - Optional context object
 * @returns {Array} tasks with aiScore, priority, and aiReason added
 */
export function prioritizeTasks(tasks, context = {}) {
    if (!Array.isArray(tasks)) return [];

    return tasks.map(task => {
        const urgency = calculateUrgency(task.dueDate);
        const categoryRisk = calculateCategoryRisk(task.category);
        const farmImpact = calculateFarmImpact(task.category);
        const aiInsights = calculateAIInsights(task, context);

        const totalScore = Math.min(Math.round(urgency + categoryRisk + farmImpact + aiInsights), 100);

        return {
            ...task.toObject ? task.toObject() : task,
            aiScore: totalScore,
            priority: scoreToPriority(totalScore),
            aiReason: generateAIReason(task, { urgency, categoryRisk, farmImpact, aiInsights })
        };
    });
}

/**
 * Sort tasks by AI score descending
 * @param {Array} tasks 
 * @returns {Array} sorted tasks
 */
export function sortByPriority(tasks) {
    return [...tasks].sort((a, b) => (b.aiScore || 0) - (a.aiScore || 0));
}

/**
 * Get top N critical tasks
 * @param {Array} tasks 
 * @param {number} n 
 * @returns {Array} top N tasks
 */
export function getTopCriticalTasks(tasks, n = 3) {
    return sortByPriority(tasks.filter(t => t.status !== 'completed')).slice(0, n);
}