/**
 * Smart Task Generator
 * 
 * Automatically creates tasks from various farm system events:
 * - Pest Detection → Treatment tasks
 * - Planting Calendar → Soil prep tasks
 * - Marketplace Orders → Delivery prep tasks
 * - Crop Suggestions → Cultivation tasks
 */

import Task from '../models/task.model.js';
import { prioritizeTasks } from './aiPrioritize.js';

/**
 * Check for duplicate tasks - prevent creating the same task within a time window
 * @param {string} farmerId
 * @param {string} source - task source
 * @param {string} category - task category
 * @param {number} hoursWindow - hours to look back (default 24)
 * @returns {boolean} true if duplicate exists
 */
async function hasDuplicateTask(farmerId, source, category, hoursWindow = 24) {
    if (!farmerId || !source) return false;
    const windowMs = hoursWindow * 60 * 60 * 1000;
    const cutoff = new Date(Date.now() - windowMs);
    const existing = await Task.findOne({
        farmer: farmerId,
        source,
        category,
        autoGenerated: true,
        createdAt: { $gte: cutoff },
        status: { $ne: 'completed' },
    });
    return !!existing;
}

/**
 * Generate a task from pest detection
 * "Treat {pest}" - High/Critical priority, due within 24-48 hours
 */
export async function generateTaskFromPestDetection(pestData, farmerId, farmId) {
    try {
        // Deduplication: skip if similar task already exists
        const isDuplicate = await hasDuplicateTask(farmerId, 'pest_detection', 'pest', 48);
        if (isDuplicate) {
            console.log('Skipping duplicate pest detection task for farmer', farmerId);
            return null;
        }

        const task = await Task.create({
            title: `Treat ${pestData.pest || 'detected pest'} infestation`,
            description: `AI-detected pest: ${pestData.pest || 'Unknown'}. Treatment: ${pestData.treatment || 'Apply recommended treatment'}. Remedies: ${(pestData.remedies || []).join(', ')}`,
            farmer: farmerId,
            farm: farmId || undefined,
            category: 'pest',
            priority: 'critical',
            status: 'pending',
            source: 'pest_detection',
            autoGenerated: true,
            dueDate: new Date(Date.now() + 48 * 60 * 60 * 1000), // 48 hours
            startDate: new Date(),
            assignedTeam: ''
        });

        // Apply AI prioritization
        const [scored] = prioritizeTasks([task], { pestSeverity: 'high' });
        return scored;
    } catch (err) {
        console.error('Failed to generate pest task:', err);
        return null;
    }
}

/**
 * Generate a task from planting calendar
 * "Prepare soil for {crop}"
 */
export async function generateTaskFromCalendar(cropData, farmerId, farmId) {
    try {
        const cropName = cropData.cropName || cropData.name || 'crop';
        const task = await Task.create({
            title: `Prepare soil for ${cropName}`,
            description: `Scheduled planting preparation for ${cropName}. ${cropData.description || ''}`,
            farmer: farmerId,
            farm: farmId || undefined,
            category: 'crop',
            priority: 'high',
            status: 'pending',
            source: 'calendar',
            autoGenerated: true,
            dueDate: cropData.plantingDate ? new Date(cropData.plantingDate) : new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
            startDate: new Date(),
            assignedTeam: ''
        });

        const [scored] = prioritizeTasks([task]);
        return scored;
    } catch (err) {
        console.error('Failed to generate calendar task:', err);
        return null;
    }
}

/**
 * Generate a task from marketplace order
 * "Prepare {product} for delivery"
 */
export async function generateTaskFromOrder(orderData, farmerId) {
    try {
        const productName = orderData.productName || orderData.product?.name || 'order';
        const task = await Task.create({
            title: `Prepare ${productName} for delivery`,
            description: `Order #${orderData.orderNumber || orderData._id || ''} needs to be prepared. Quantity: ${orderData.quantity || 'N/A'}. Customer: ${orderData.buyer?.name || 'N/A'}`,
            farmer: farmerId,
            farm: orderData.farm || undefined,
            category: 'orders',
            priority: 'high',
            status: 'pending',
            source: 'order',
            autoGenerated: true,
            dueDate: orderData.deliveryDate ? new Date(orderData.deliveryDate) : new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
            startDate: new Date(),
            assignedTeam: ''
        });

        const [scored] = prioritizeTasks([task], { orderDeadlineNear: true });
        return scored;
    } catch (err) {
        console.error('Failed to generate order task:', err);
        return null;
    }
}

/**
 * Generate a task from AI crop suggestion
 */
export async function generateTaskFromCropSuggestion(suggestionData, farmerId, farmId) {
    try {
        // Deduplication: skip if similar task already exists
        const isDuplicate = await hasDuplicateTask(farmerId, 'ai', 'crop', 168);
        if (isDuplicate) {
            console.log('Skipping duplicate crop suggestion task for farmer', farmerId);
            return null;
        }

        const cropName = suggestionData.cropName || suggestionData.crop || 'recommended crop';
        const task = await Task.create({
            title: `Plan cultivation for ${cropName}`,
            description: `AI-suggested crop: ${cropName}. ${suggestionData.reason || suggestionData.description || ''}`,
            farmer: farmerId,
            farm: farmId || undefined,
            category: 'crop',
            priority: 'medium',
            status: 'pending',
            source: 'ai',
            autoGenerated: true,
            dueDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000), // 2 weeks
            startDate: new Date(),
            assignedTeam: ''
        });

        const [scored] = prioritizeTasks([task]);
        return scored;
    } catch (err) {
        console.error('Failed to generate crop suggestion task:', err);
        return null;
    }
}