import mongoose from 'mongoose';

const TaskSchema = new mongoose.Schema({
    title: {
        type: String,
        required: true
    },
    description: {
        type: String,
        default: ''
    },
    farmer: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    farm: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Farm'
    },
    category: {
        type: String,
        enum: [
            'planting',
            'maintenance',
            'harvesting',
            'watering',
            'fertilizing',
            'pest_control',
            'irrigation',
            'weeding',
            'monitoring',
            'other',
            'crop',
            'pest',
            'harvest',
            'orders',
            'equipment',
            'inventory',
            'manual'
        ],
        default: 'other'
    },
    priority: {
        type: String,
        enum: ['low', 'medium', 'high', 'critical'],
        default: 'medium'
    },
    status: {
        type: String,
        enum: ['pending', 'in_progress', 'completed', 'overdue', 'scheduled'],
        default: 'pending'
    },
    dueDate: {
        type: Date
    },
    startDate: {
        type: Date
    },
    endDate: {
        type: Date
    },
    assignedTeam: {
        type: String,
        default: ''
    },
    notes: {
        type: String,
        default: ''
    },
    // Smart Farm Task System fields
    source: {
        type: String,
        enum: ['manual', 'calendar', 'pest_detection', 'order', 'ai'],
        default: 'manual'
    },
    aiScore: {
        type: Number,
        default: 0,
        min: 0,
        max: 100
    },
    aiReason: {
        type: String,
        default: ''
    },
    autoGenerated: {
        type: Boolean,
        default: false
    }
}, {
    timestamps: true
});

// Performance indexes
TaskSchema.index({ farmer: 1, dueDate: 1 });
TaskSchema.index({ farmer: 1, status: 1 });
TaskSchema.index({ farmer: 1, source: 1 });

const Task = mongoose.model('Task', TaskSchema);

export default Task;


